feat: add new empty api container
neojelll/url-shortener pull request #7
Opened 2024-09-01 20:21 UTC by neojelll

2024-09-04 20:11 UTC, symflood commented on api/api/__init__.py
> +#создание приложения
Не пиши банальные коменты )

2024-09-04 20:13 UTC, symflood commented on api/api/__init__.py
> +url_dict = {}
Это я не понимаю зачем. Ты управление получишь в апи, там создашь объект, отправишь в топик

2024-09-04 20:13 UTC, symflood commented on api/api/__init__.py
> +#проверка ссылки на коректность
Удалить

2024-09-04 20:15 UTC, symflood commented on api/api/__init__.py
> +    return all([parsed_url.scheme, parsed_url.netloc])
Кмк тут можно упростить до возврата `true`/`false` в зависимости от того есть ли исключение при парсинге или нет

2024-09-04 20:15 UTC, symflood commented on api/api/__init__.py
> +#запрос из cURL or TelegramBot
Удалить

2024-09-04 20:16 UTC, symflood commented on api/api/__init__.py
> +#запрос из кафки
Удалить

2024-09-04 20:16 UTC, symflood commented on api/api/__init__.py
> +    Task: Task-num
Нужно придерживаться одного стиля

2024-09-04 20:17 UTC, symflood commented on api/api/__init__.py
> +async def post_url(url_dict: Dict[str, str]):
Нужно свалидировать JSON документ

2024-09-04 20:19 UTC, symflood commented on api/api/__init__.py
> +    url: str = url_dict.setdefault("url", "")
Не понимаю что это. `.get('url', '')`?

2024-09-07 09:25 UTC, symflood commented on api/api/main.py
> +}
Замени это на BaseModel сабкласс

2024-09-07 09:25 UTC, symflood commented on api/api/main.py
> +        return False
Не нужно валидировать если использовать `BaseModel` и офлоадить валидацию FastAPI

2024-09-07 09:28 UTC, symflood commented on api/api/main.py
> +@app.get("/prefix-shorturl")
не "/prefix-shorturl" а 

```
@app.get("/{short_id}")
async def transport_to_long_url(short_id: str):
...
```

2024-09-07 09:31 UTC, symflood requested changes

2024-09-07 09:31 UTC, symflood commented on api/api/main.py
> +        return False
https://fastapi.tiangolo.com/tutorial/body/

2024-09-07 09:44 UTC, symflood commented on api/api/main.py
> +    raise HTTPException(status_code=400, detail="don`t correct url")
https://fastapi.tiangolo.com/reference/status/

Используй встроенные статусы, не hardcoded числа

2024-09-08 18:59 UTC, symflood commented on api/api/main.py
> +                        detail="don`t correct url")
"Invalid URL"

2024-09-08 19:01 UTC, symflood commented on api/pyproject.toml
> +
Тут достаточно одного вертикального отступа вместо трех

2024-09-08 19:01 UTC, symflood commented on api/pyproject.toml
> +
Тож самое

2024-09-08 19:02 UTC, symflood commented on .github/workflows/auto-run-ruff.yaml
> +on: [push]
Пуск по изменениям файлов в проекте api, не во всей репе

2024-09-08 19:02 UTC, symflood commented on .github/workflows/auto-run-ruff.yaml
> +       pip install -r requirements.txt
Нужно использовать poetry для установки зависимостей, не pip

2024-09-08 19:03 UTC, symflood requested changes

2024-09-08 19:03 UTC, symflood commented on .github/workflows/auto-run-ruff.yaml
> +        ruff check api/api/main.py
Проверять нужно все Python файлы директории проекта. Нужно обдумать как ее получить

2024-09-08 19:07 UTC, symflood commented
Нужен общий интеграционный пайплайн для изменений в проекте
* Статический анализ (для изменений в feature ветке)
* Юнит тесты (для изменений в feature ветке)
* Интеграционные тесты (для мерж комита)
* Выпуск артефактов: пакет и докер образ (для мерж коммита)

2024-09-11 18:56 UTC, symflood commented on api/api/main.py
> +    print(parsed_url)
Не делай таких принтов в коде

2024-09-16 20:22 UTC, symflood requested changes
<img width="788" alt="image" src="https://github.com/user-attachments/assets/3c70a44a-13d8-4e3c-8c09-9de6b8ff6d90">

Для api.py покрытие по строкам нужно 100%

2024-09-16 20:22 UTC, symflood commented on api/tests/test_api.py
> +	assert response.status_code == status.HTTP_302_FOUND
Тут очевидно тестируется только happy path. Нужно написать тесты для недоступной записи в кеше, недоступной в базе

2024-09-16 20:22 UTC, symflood commented on api/pyproject.toml
> +httpx = "^0.27.2"
Нужен плагин для оценки покрытия

`poetry add --group=dev pytest-cov`
`poetry run pytest --cov-report term-missing --cov=api tests`

2024-09-16 20:27 UTC, symflood commented on api/pyproject.toml
> +httpx = "^0.27.2"
Ну и схему связи между контейнерами нужно поправить. Редирект идет через обращение к стореджу

2024-09-21 14:46 UTC, symflood requested changes
Мне не ясно как обрабатывается случай если ссылка истекла

2024-09-21 14:46 UTC, symflood commented on api/pyproject.toml
> +ignore = ["E501"]  # Игнорируйте ошибки с указанным кодом (например, длинные строки)
убери тут коментарии

2024-09-21 14:46 UTC, symflood commented on architecture/c4-model.dsl
> +            Api -> DataBase "select data"
request long url

2024-09-21 14:46 UTC, symflood commented on architecture/c4-model.dsl
> +            Api -> Cache "select data"
try to request long url from db cache

2024-09-21 16:19 UTC, symflood commented on .gitignore
> +.coverage
директории скипаются как `PATH/`
ты скипнул и файл с настройками и его нет в репе

2024-09-21 16:20 UTC, symflood commented on api/api/db.py
> +            long_url = await self.session.execute(
это скорее результат запроса `result` а не `long_url`

2024-09-21 16:26 UTC, symflood commented on api/api/db.py
> +            long_url = await long_url.first()
я не вижу в документации что это асинхронные методы

https://docs.sqlalchemy.org/en/20/orm/session_api.html#sqlalchemy.orm.Session.scalar

посмотри ветку `db-tests-fix`

2024-09-21 20:48 UTC, symflood commented on api/.coveragerc
> +    api/__init__.py
это не нужно, если файл пустой

2024-09-26 18:49 UTC, symflood commented
Нуж поправить отступы в файлах. Дичь какая-то. Где-то табы, где-то пробелы. Больно смотреть

2024-09-26 19:42 UTC, symflood commented on api/api/api.py
> +                expiration = await database.get_expiration(short_url)
Тут фактически 2 запроса вместо одного? Можно сделать лучше?

2024-09-26 19:45 UTC, symflood requested changes

2024-09-26 19:45 UTC, symflood commented on api/api/api.py
> +            await cache.set(short_url, long_url, expiration / 3600)
Это обсуждалось, экспирация в БД может быть сотня часов. В кеш ты ложишь на короткое время которое задается через окружение, либо на остаток времени который остался до экспирации (меньший из интервалов)

2024-09-26 20:00 UTC, symflood commented on api/api/api.py
> +            await cache.set(short_url, long_url, expiration / 3600)
Ты передаешь `expiration` всегда просто из базы, что неверно, передавать нужно `max((creation_datetime + expiration) - current_datetime, 0)`

Примеры:

---

ссылка создана в 01h00m, время экспирации 1h, сейчас 01h30m

у тебя выйдет что ты передашь в функцию кеша 1 час, тогда как осталось `max((01h00m + 1h) - 01h30m, 0) = max(30, 0) = 30min`

---

ссылка создана в 01h00m, время экспирации 1h, сейчас 02h00m

у тебя выйдет что ты передашь в функцию кеша 1 час, тогда как осталось `max((01h00m + 1h) - 02h00m, 0) = max(0m, 0) = 0`

2024-09-27 07:41 UTC, neojelll commented on api/api/api.py
> +                expiration = await database.get_expiration(short_url)
ну сессия то не закрывается а разбить на 2 метода удобней

2024-09-29 09:12 UTC, symflood approved these changes

2024-09-29 09:13 UTC, merged